// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyTransfer.Api.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoneyTransfer.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    partial class LedgerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoneyTransfer.Api.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowsNegative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allows_negative");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("OwnerRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_ref");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Currency")
                        .HasDatabaseName("ix_accounts_currency");

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("currency_alpha", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("currency_upper", "currency = upper(currency)");
                        });
                });

            modelBuilder.Entity("MoneyTransfer.Api.Domain.Balance", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<long>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("version");

                    b.HasKey("AccountId")
                        .HasName("pk_balances");

                    b.ToTable("balances", (string)null);
                });

            modelBuilder.Entity("MoneyTransfer.Api.Domain.LedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TxId")
                        .HasColumnType("uuid")
                        .HasColumnName("tx_id");

                    b.HasKey("Id")
                        .HasName("pk_ledger_entries");

                    b.HasIndex("TxId")
                        .HasDatabaseName("ix_entries_tx");

                    b.HasIndex("AccountId", "Id")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_entries_account_id_desc");

                    b.ToTable("ledger_entries", null, t =>
                        {
                            t.HasCheckConstraint("amount_bounded", "abs(amount) BETWEEN 1 AND 1000000000000000");

                            t.HasCheckConstraint("amount_nonzero", "amount <> 0");
                        });
                });

            modelBuilder.Entity("MoneyTransfer.Api.Domain.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RequestHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("request_hash")
                        .IsFixedLength();

                    b.Property<Guid?>("ReversedTxId")
                        .HasColumnType("uuid")
                        .HasColumnName("reversed_tx_id");

                    b.HasKey("Id")
                        .HasName("pk_transfers");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_transfers_created_at");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_transfers_idem")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("ReversedTxId")
                        .IsUnique()
                        .HasDatabaseName("ux_transfers_reversed_once")
                        .HasFilter("reversed_tx_id IS NOT NULL");

                    b.ToTable("transfers", null, t =>
                        {
                            t.HasCheckConstraint("kind_valid", "kind IN ('transfer','deposit','withdrawal','reversal')");
                        });
                });

            modelBuilder.Entity("MoneyTransfer.Api.Domain.Balance", b =>
                {
                    b.HasOne("MoneyTransfer.Api.Domain.Account", "Account")
                        .WithOne("Balance")
                        .HasForeignKey("MoneyTransfer.Api.Domain.Balance", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_balances_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MoneyTransfer.Api.Domain.LedgerEntry", b =>
                {
                    b.HasOne("MoneyTransfer.Api.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_accounts_account_id");

                    b.HasOne("MoneyTransfer.Api.Domain.Transfer", "Transfer")
                        .WithMany("Entries")
                        .HasForeignKey("TxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_transfers_tx_id");

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("MoneyTransfer.Api.Domain.Transfer", b =>
                {
                    b.HasOne("MoneyTransfer.Api.Domain.Transfer", null)
                        .WithMany()
                        .HasForeignKey("ReversedTxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transfers_transfers_reversed_tx_id");
                });

            modelBuilder.Entity("MoneyTransfer.Api.Domain.Account", b =>
                {
                    b.Navigation("Balance")
                        .IsRequired();
                });

            modelBuilder.Entity("MoneyTransfer.Api.Domain.Transfer", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
